# Generated by Django 5.2.17 on 2026-10-08 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='user_id',
            new_name='user',
        ),
    ]
