# Generated by Django 5.2.17 on 2026-09-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
